name: shaw_solutions
description: "A new Flutter project."

# Prevent package from being accidentally published to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.6

  # Firebase dependencies
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  firebase_messaging: ^15.1.1

  # For state management
  provider: ^6.0.5

  # WebSocket for real-time messaging
  web_socket_channel: ^2.1.0

  # Stripe integration for payments
  flutter_stripe: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  # Uncomment to add custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf