// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnZxXxfT1sGjEShETm_vDR7cjxTCKbYZc',
    appId: '1:1012219230958:web:6f92aef482d08736bd51ff',
    messagingSenderId: '1012219230958',
    projectId: 'shaw-solutions',
    authDomain: 'shaw-solutions.firebaseapp.com',
    storageBucket: 'shaw-solutions.appspot.com',
    measurementId: 'G-VDH22GP2P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Y_BbaFKT44iEdNqlUp0m4i44ijwMXNA',
    appId: '1:1012219230958:android:d19e44f317b71fd9bd51ff',
    messagingSenderId: '1012219230958',
    projectId: 'shaw-solutions',
    storageBucket: 'shaw-solutions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLNyiLDr3Re90Jcy_kqJkNvHz-awIhzzo',
    appId: '1:1012219230958:ios:a1eb1b432d6da1c9bd51ff',
    messagingSenderId: '1012219230958',
    projectId: 'shaw-solutions',
    storageBucket: 'shaw-solutions.appspot.com',
    iosBundleId: 'info.hunterstevenshaw.shawSolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLNyiLDr3Re90Jcy_kqJkNvHz-awIhzzo',
    appId: '1:1012219230958:ios:bd0fb8b35b3a5323bd51ff',
    messagingSenderId: '1012219230958',
    projectId: 'shaw-solutions',
    storageBucket: 'shaw-solutions.appspot.com',
    iosBundleId: 'com.example.shawSolutions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnZxXxfT1sGjEShETm_vDR7cjxTCKbYZc',
    appId: '1:1012219230958:web:fb93417291aff010bd51ff',
    messagingSenderId: '1012219230958',
    projectId: 'shaw-solutions',
    authDomain: 'shaw-solutions.firebaseapp.com',
    storageBucket: 'shaw-solutions.appspot.com',
    measurementId: 'G-RKBEKNB1K2',
  );
}
